import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from '~/app/providers'
import { x } from '@xstyled/styled-components'
import { Sidebar } from '~/components/global/sidebar/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'nextjs-app-router',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <div className="global_layout">
            <Sidebar />
            {children}
          </div>
        </body>
      </html>
    </Providers>
  )
}
